### ISSUE TITLE
Wiring Scmatics for ESP 01

### ISSUE THREAD

**Issue by wranglatang** [johnboiles/esp-roomba-mqtt#12]
Hello,

Would it be possible to post a wiring Scmatics & Config changes required for use with an ESP 01?

I seen another video online from The Hookup where Rob uses a PNP transistor and a buck converter. I’m wondering why you use all the resistors? 

Apologies, my electronic knowledge is not great!

**Comment by iago-veiga** [comment]
Hi! 
You can use this image from https://domology.es/domotizando-nuestra-vieja-roomba-serie-5-6-con-esp-01-y-mqtt/ I use it with sucessful. The model of transistor is PNP 2N3906
![Image ES-01](https://domology.es/wp-content/uploads/2018/11/schematic.jpg)

Remember change platformio.ini like
```
[env:esp01_1m]
platform = espressif8266
framework = arduino
board = esp01_1m
lib_deps =
  RemoteDebug
  PubSubClient
  ArduinoJson@^5.13.4
build_flags = -DLOGGING=1 -DMQTT_MAX_PACKET_SIZE=512

```
And  you can USE BRC_PIN as PIN 2
