### ISSUE TITLE
Not Working after Upload to D1 Mini

### ISSUE THREAD

**Issue by wranglatang** [johnboiles/esp-roomba-mqtt#13]
I have uploaded the code on a D1 Mini board and it doesn't appear to work.

If i monitor the serial out i can see
`--- Miniterm on /dev/cu.usbserial-1410  9600,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
,E����dGI�0lK��␄i�␞H␡����Ȍ!C����V)��3���T!��4�B�P�j���������������������������������\��������������������������������������޿��������������n���ʿ�������\��������������q��R8���d:w����␌!��␎��f闍␙���v��!�K��b��\�l�������������������������������\��T����������������ş�����������l�������ղ�����������ڱ����������������������������?3�b(��`;G������E�����)��7��!!�:�TD�j�����������d���������������������\�������������������������������������ڌ�������Ų��������?��������������������l�����u��V(�)�D
�������E���␙�ť�7�1!��*�␚����U�����������������������܍�������������������ʲ���g��������������������ݸ������������F�܌�������������������l�����u���)�D`

I also don't get any messages published to the MQTT Topic.

**Comment by johnboiles** [comment]
Did you set the correct wifi credentials in secrets.h? Do you see the D1 Mini show up in your routers admin page? Can you `ping roomba.local` from your computer? That output just looks like you have the wrong baud rate set. Try 115200

**Comment by egebaek** [comment]
have the same problem, cannot see it in the DHCP table, the Wifi credentials i correct, gets this from the Serial monitor on 115200:
sd[00]dœŸ|[00]„là|[03][04][04][0C]Œ[04]$ì[0C]b|‚[03]ä[1B]’s›cŒ[0C]bÄògnŸlgnœâä[04]b[1C]pŒŽdsd{lpûgà[10][03][0C][0C]ƒ[04]l[0C]„œ[0C][0C][04]c[0C]gã|[03]lì[04][04]‡c„ûogç[00]$ŒÇd`[03]Ø[13][1B]gg[04]$`[02][07][03]o;‡“›o[0C][0C]c[04]œ[0F]$[0F]{’“n[0C][0C]c[04]œ[0E]dœ[1B]l‡p[02]›ãâ[13]›`[02]ü‚gœ[03]

have this building log:
Processing d1_mini (platform: espressif8266; board: d1_mini; framework: arduino)
 
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266  WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz 80KB RAM (4MB Flash)
Library Dependency Finder - http://bit.ly/configure-pio-ldf

LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 33 compatible libraries
Scanning dependencies...
Dependency Graph
|-- RemoteDebug 1.5.8
|   |-- ESP8266WiFi 1.0
|-- PubSubClient 2.7
|-- ArduinoJson 5.13.4
|-- Roomba
|-- ESP8266WiFi 1.0
|-- ArduinoOTA 1.0
|   |-- ESP8266WiFi 1.0
|   |-- ESP8266mDNS 1.2
|   |   |-- ESP8266WiFi 1.0
|-- ESP8266mDNS 1.2
|   |-- ESP8266WiFi 1.0
