### ISSUE TITLE
Disable default wifi hotspot

### ISSUE THREAD

**Issue by alqa-dash** [johnboiles/esp-roomba-mqtt#34]
Hello! Great project! Finally may be I can get a remote control to my 500 old guy :)

But I have a question: I successfully compiled and uploaded firmware to esp card. Booted it then and connected to it using telnet. Seems to be ok so far. But what I don't understand - is when card is booted I see AI-THINKER_xxxxx wifi hotspot with no security provided. Can you tell me how to turn off that wifi? 

Regards,
Dash

**Comment by alqa-dash** [comment]
Solved by myself. Thanks.

**Comment by GusGom** [comment]
How did you solve it? 
Thank you.

**Comment by alqa-dash** [comment]
main.cpp

```
setup() {
...
  WiFi.enableAP(false);
...
}
```
